FROM node as build

WORKDIR /app

COPY package.json .

RUN npm i

COPY . .

RUN npm run build

FROM nginx

WORKDIR /etc/nginx

RUN rm nginx.conf

COPY /nginx.conf /etc/nginx/

WORKDIR /var/www/awsDockerAtlas

COPY --from=build /app/build /var/www/awsDockerAtlas

CMD ["nginx", "-g", "daemon off;"]